### ISSUE TITLE
NavLink use instead of Link

### ISSUE THREAD

**Issue by j8seangel** [rafrex/react-router-hash-link#10]
Hi !

I've forked the library because I consider useful to use NavLink component instead of Link because I'm using this https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/NavLink.md#isactive-func to mark the active section.

Let me know your thoughts and I could prepare a PR and thanks!

**Comment by rafrex** [comment]
Hi, sorry for the late response, was on vacation.

It'd be great to support NavLinks too. Let's export two components, `HashLink` and `NavHashLink`, with the API remaining the same. The code could look like this:

```js
function genericHashLink(props, As) {
  // same as current HashLink function...
  return <As {...props}  onClick={handleClick}>{props.children}</As>;
}

export function HashLink(props) {
 return genericHashLink(props, Link);
}

export function NavHashLink(props) {
  return genericHashLink(props, NavLink);
}
```

**Comment by shawnmmatthews** [comment]
Hi, has this been implemented in the current version, or is the fork available?

**Comment by rafrex** [comment]
I added `<NavHashLink>` in `v1.2`, see readme for details.
