### ISSUE TITLE
Scroll with offsett?

### ISSUE THREAD

**Issue by vhflat** [rafrex/react-router-hash-link#12]
Is it possible to add an offsett to the scroll, in case of sticky navbar etc. ?

**Comment by rafrex** [comment]
We're working on the ability to pass in as props a custom scroll function that would be called with the element to scroll to. Once this is released, you can create a custom scroll function that will scroll with offset.

**Comment by BDMayhem** [comment]
In the meantime, you can hardcode your header height, and have it scroll down that much every time.

Found here: https://stackoverflow.com/questions/13614112/using-scrollintoview-with-a-fixed-position-header/13857312#13857312

In /lib/index.js after element.scrollIntoView(); add:

    var scrolledY = window.scrollY;

    if(scrolledY){
      window.scroll(0, scrolledY - '[your header height in pixels]');
    }

**Comment by rafrex** [comment]
I implemented a custom scroll function in `v1.2`, see readme for docs.
