### ISSUE TITLE
Add type definitions?

### ISSUE THREAD

**Issue by EliRobinson** [rafrex/react-router-hash-link#14]
Hello,
Just a quick question about whether you plan to create typescript/flow type definitions for this package.

Thanks for doing this! Helped a ton.

**Comment by rafrex** [comment]
No. But feel free to add them to the respective centralized type definition repo for everyone to use!

**Comment by EliRobinson** [comment]
Will look into that, thanks

**Comment by zoompie** [comment]
Hi,

I made a PR to DefinitelyTyped to support types, it got approved yesterday.

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-router-hash-link

You can add them using npm install --dev @types/react-router-hash-link
