### ISSUE TITLE
Extra Smooth

### ISSUE THREAD

**Issue by 0xClpz** [rafrex/react-router-hash-link#17]
I like the smooth props, do you think you could provide us with an extraSmooth prop? I'd like to impress my colleagues,

Thanks,

**Comment by rafrex** [comment]
No, but you can create a custom scroll function that scrolls as slow as you'd like, and use it with the `scroll` prop.

The `smooth` prop just uses the `scrollIntoView(options)` smooth option, so the browser controls the speed at which it scrolls.
