### ISSUE TITLE
Page jumping to top first, and also scrolling to an odd spot of the target element

### ISSUE THREAD

**Issue by lucastobrazil** [rafrex/react-router-hash-link#18]
Love that you created and shared this! Thank you 🙏 

Having some trouble getting it to work the same as the examples:
- My links aren't at the top of the page, so the user has to scroll a bit first. When clicking on a `HashLink`, it jumps to the top of the page first, then scrolls.
- When it does scroll, it scrolls halfway through the container (so the top is about -X pixels from the top of the viewport. 

I have got some inner padding on the sections, but it seems that in the example this is fine too.

Any ideas?

https://lucastobrazil.github.io/portfolio

**Comment by rafrex** [comment]
I'd create a custom scroll function and pass it into the `scroll` prop. This way you can scroll with offset, etc. `HashLink` just uses the element method `el.scrollIntoView()`, so if it it's not working, the error is in the element method, not `HashLink`.

**Comment by lucastobrazil** [comment]
@rafrex thanks for your reply. Ill check that out. Is it possible to see the source code for your example page anywhere? Does that use a custom scroll function?

**Comment by rafrex** [comment]
The example site is in the `gh-pages` branch. It doesn't use a custom scroll function. You could look at the polyfill for `scrollIntoView` for some ideas, or find another smooth scrolling library whose scroll function to use with `HashLink`.

**Comment by skylerbala** [comment]
anyone figure out a solution for this?

**Comment by hien-q-nguyen** [comment]
unfortunately no solution

**Comment by rafgraph** [comment]
Can someone create a reproduction of this in codesandbox?
