### ISSUE TITLE
Scroll or smooth attribute error

### ISSUE THREAD

**Issue by Smaug333** [rafrex/react-router-hash-link#19]
Hello,
Thanks for this package!
 
When adding a scroll function like 
```
<Link
  to="/#start"
  scroll={el => el.scrollIntoView({ behavior: 'smooth', block: 'end' })}>
  start
</Link>
```
I get this error and the function will not fire
```Warning: Invalid value for prop `scroll` on <a> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM  (...)```

adding the "smooth" attribute like your example will produce this error and no animation is triggered 
```Warning: Received `true` for a non-boolean attribute `smooth`. If you want to write it to the DOM, pass a string instead: smooth="true" or smooth={value.toString()}. (...)```

from my package.json:
```
"react": "^16.2.0",
"react-router-dom": "^4.2.2",
"react-router": "^4.2.0",
```
Am I missing something? Ideas?

Thanks

**Comment by rafrex** [comment]
It sounds like your using an old version of `react-router-hash-link`. You need to use version `1.2.0` for scrolling features.

**Comment by Smaug333** [comment]
oh great, that's it! Thanks a lot!
