### ISSUE TITLE
target="_blank" breaks the anchor links 

### ISSUE THREAD

**Issue by Indyandie** [rafrex/react-router-hash-link#22]
If I add `target="_blank"`  it just links to the top of the page. It's probably something obvious, but wondering if anyone encountered the same issue.

**Comment by rafrex** [comment]
I don't think React Router's `<Link>` supports `target="_blank"` since it's for push state routing (all props are passed through to `<Link>`. Just use a normal `<a>` if you want to open something in a new browser window.
