### ISSUE TITLE
NavHashLink no longer passing aria prop through Route

### ISSUE THREAD

**Issue by greypiglet** [rafrex/react-router-hash-link#28]
Hi there, great plugin, many thanks! Would be most grateful if anyone can highlight why the below might be occurring.

In an earlier build of my app I was passing an aria prop through NavHashLink to set the active state of a link, which resulted in the following markup...

![image](https://user-images.githubusercontent.com/6341474/41652964-9794355a-747c-11e8-81b8-899f8ca2bfaa.png)

I believe that after updating React to 16.3, this no longer happens, and results in markup like this...

![image](https://user-images.githubusercontent.com/6341474/41653001-b1dc11f8-747c-11e8-93bf-2689221faa44.png)

Both examples use the same version of react-router-hash-link (1.2.0), react-router (4.2.0) and react-router-dom (4.2.2). As far as I can tell the only thing that's changed is upgrading React.

Seems strange that the aria attribute is passed through still but with a value of null :s

**Comment by rafrex** [comment]
Hi, this appears to be an issue with `react-router-dom` (or maybe `react`) and not this library. In your screen shot the `aria-current` is correctly passed to the `NavLink` component which is part of `react-router-dom`, which is all this library can control.
