### ISSUE TITLE
Scrolls to bottom of element rather than top in IE11

### ISSUE THREAD

**Issue by robatwilliams** [rafrex/react-router-hash-link#30]
`alignToTop = true` is the default: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView

It appears that the passing of `undefined` here is being interpreted as `false`: https://github.com/rafrex/react-router-hash-link/blob/master/src/index.js#L68

**Comment by robatwilliams** [comment]
Workaround: pass a `scroll` prop with a function `element => element.scrollIntoView()`

**Comment by rimatla** [comment]
@robatwilliams I'm on the same boat, could you pls post your workaround solution?

**Comment by rafrex** [comment]
This should be fixed now in v1.2.1
