### ISSUE TITLE
NavHashLink doesn't work when "to" gets object passed

### ISSUE THREAD

**Issue by Poky85** [rafrex/react-router-hash-link#32]
Original React Router's `<Link>` accept to parameter of object type. `NavHashLink` from react-router-hash-link also accepts object but activeClassName parameter doesn't work in such case (is always applied event if link is not active).

```javascript
<NavHashLink
    activeClassName="active"
    to={{
        pathname: "/foo",
  }}
>
    Anchor
</NavHashLink>
```

**Comment by dougtribe** [comment]
Yeah this would be a good fix. It's much nicer to use an object to preserve, say, location.search rather than string building

**Comment by rafrex** [comment]
This is an issue with React Router, it seems like the fix is merged in master but not released yet.
See ReactTraining/react-router#6877

**Comment by rafrex** [comment]
Closing and tracking in #41
