### ISSUE TITLE
Doesn't work in Firefox

### ISSUE THREAD

**Issue by high-noroque** [rafrex/react-router-hash-link#33]
Discovered it doesn't work in Firefox when cross browser testing. In Chrome, Safari and Opera acts as expected.

**Comment by high-noroque** [comment]
False alarm. Can you please close this issue? I've just realised I made a mistake by wrapping the Link tag in a button.

**Comment by VIBHOR94** [comment]
@high-noroque  I have checked it on Firefox 63.0.3 (64-bit). Its working
