### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by krystofbe** [rafrex/react-router-hash-link#46]
Hey @rafrex! 

Thanks for this awesome lib.

There are some open Issues and PRs. Would you mind reviewing them or think about adding more collaborators (Would offer my help!)?

**Comment by rafrex** [comment]
Hi, yes this is still maintained. Thanks for your offer to help. Feel free to respond to issues and PRs.

Something that would be helpful is to create a basic example app in CodeSandbox that others can use as a starting point to create failing examples for their issues. It is so much easier to diagnose an issue when there is a live failing example.
