### ISSUE TITLE
<NavHashLink to='/'>Home</NavHashLink> does not scroll to the top of the page when clicked after a hash link

### ISSUE THREAD

**Issue by Vidit92** [rafrex/react-router-hash-link#49]
`<Link to="/">Home</Link>`
`<Link smooth to="/#sectiontwo">Two</Link>`
`<Link smooth to="/#sectionthree">Three</Link>`

The link to the hash is working perfectly, but after I have scrolled to the hash and when I click Home it is expected to scroll back to the top, but nothings happens.

Please help, me find the solution to these problem. 
CodeSandbox: [https://codesandbox.io/s/busy-sinoussi-7w73c](url)

**Comment by rafrex** [comment]
That's because there's no hash for it to scroll to when you click Home. Whenever you want to scroll, the element you want to scroll to has to have an `id` that matches the hash in the link. You could add a `id="home"` to the top element, and use `<Link to="/#home">Home</Link>` for the link.
