### ISSUE TITLE
Long Onepage Scroll Problem

### ISSUE THREAD

**Issue by tulindor** [rafrex/react-router-hash-link#59]
I'am currently developing a one page, that has a main component with the correspondent secctions inside, and then I have a Portfolio component that renders in other instance.

The problem is, when i came back from the component Portfolio to a Hashlink pointing to a secction, it stops halfway, not currently in the top or the bottom, it happens only with the last 2 items.

**Comment by rafrex** [comment]
Hi I'm going need a failing example in order to diagnose the issue. Thanks.

**Comment by tulindor** [comment]
I just give up, and create my navigation in other way, when i create a new react proyect with custom CSS it worked awesome, but whenever i implement bootstrap it have this error, i think it may be something with flexbox or something else...
