### ISSUE TITLE
Error in ../~/react-router-hash-link/lib/index.js Module not found: 'react' in

### ISSUE THREAD

**Issue by platedodev** [rafrex/react-router-hash-link#6]
Hi there, I can't import HashLink. I'm getting this error:
Failed to compile.

Error in ../~/react-router-hash-link/lib/index.js
Module not found: 'react' in /home/mdossantos/***/***/node_modules/react-router-hash-link/lib

 @ ../~/react-router-hash-link/lib/index.js 13:13-29

I'm using react 15.5.4 and react-router-dom 4.1.1.

**Comment by rafrex** [comment]
`react` is a peer dependency, so it should be in `/home/mdossantos/***/***/node_modules`. Make sure webpack is set up to look up the directory tree to resolve dependencies (be default it will do this and should work without issue). Also, try deleting `node_modules` and running `$ npm install`.
