### ISSUE TITLE
How to remove the hash link from history

### ISSUE THREAD

**Issue by tomcanac** [rafrex/react-router-hash-link#62]
Hi,
First thanks for the packages, does great job!

My question is, how should I handle removing the hash url from history? Basically I want that my back button goes back to the previous page, skipping any sub hash navigation in my current page. What would be the clean way to do this?

Thanks for the help

**Comment by rafrex** [comment]
Use `replace` prop. See https://reacttraining.com/react-router/web/api/Link/replace-bool

**Comment by tomcanac** [comment]
Thanks a lot!
